- name: NGINX | Restarted service for systemd
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
    daemon_reload: true
  when: ansible_facts.service_mgr == "systemd" and ansible_facts.virtualization_type != "docker" and ansible_facts.virtualization_type != "podman"

- name: NGINX | Restarted service for sysvinit
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
  when: ansible_facts.service_mgr == "sysvinit" and ansible_facts.virtualization_type != "docker" and ansible_facts.virtualization_type != "podman"
