- name: NGINX | Restarted service for systemd
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: true
  when: ansible_facts.virtualization_type != "docker" and ansible_facts.virtualization_type != "podman"
