---
# handlers file for roles/nginx
- name: NGINX | Restarted service for sysvinit
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: ansible_facts.service_mgr == "sysvinit"